

services:

  app:
    build:
      context: .

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_NAME: db_app
      DB_USER: db_user
      DB_PASS: db_pass


  db:
    image: postgres:15-alpine3.16
    restart: always
    environment:
      POSTGRES_PASSWORD: db_pass
      POSTGRES_USER: db_user
      POSTGRES_DB: db_app

  redis:
    image: redis:6.0-alpine
    restart: always
    hostname: redis


  worker1:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis

  worker2:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - redis
