# Generated by Django 4.2.11 on 2024-04-21 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=0, max_length=255, unique=True, verbose_name='Токен')),
                ('user_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реферальная программа - Токен',
                'verbose_name_plural': 'Реферальная программа - Токен',
                'ordering': ['user_owner'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.referralprogram', verbose_name='Токен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Реферал')),
            ],
            options={
                'verbose_name': 'Рефералы',
                'verbose_name_plural': 'Рефералы',
                'ordering': ['referral_token'],
            },
        ),
    ]
